apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2017-04-19T15:37:12Z
  generation: 2
  labels:
    app: bbtest
  name: bbtest
  namespace: default
  resourceVersion: "2741364"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/bbtest
  uid: 0ebc7858-2516-11e7-809a-0e6145ad429e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbtest
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bbtest
    spec:
      containers:
      - image: bbenns/wedding-website
        imagePullPolicy: Always
        name: wedding-website
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-04-19T15:37:12Z
    lastUpdateTime: 2017-04-19T15:37:12Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
